### ISSUE TITLE
UI: Design Mockups

### ISSUE THREAD

**Issue by Kuszter** [bprof-spec-codes/proggame#7]

**Comment by davidgyongyosi** [comment]
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/a0477a44-5f04-47a5-8f15-f0c27777dff7)
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/0afa5067-c39d-4245-aa1a-3ed056993258)
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/28f3519e-82a2-4f08-af2f-f6b1f0f39f88)
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/4097ad23-fad4-4fcc-abd7-6df28a8acd0e)
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/ebd43f45-089f-4e3a-abc7-960091217dc7)
![Image](https://github.com/bprof-spec-codes/proggame/assets/43970367/4ad02f79-fc4a-40f6-a8e3-b8a9f122c261)
